### ISSUE TITLE
Script dies same point every time

### ISSUE THREAD

**Issue by Drazzilb08** [BreadedChickenator/Cross-Seed-AutoDL#12]
Error:
```
Searching for 100 of 1870: The Increasingly Poor Decisions of Todd Margaret 
Traceback (most recent call last):
  File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 375, in <module>
    main()
  File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 347, in main
    matching_results = searcher.search(local_release_data, search_history)
  File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 137, in search
    self.search_results = self._trim_results( resp_json['Results'] )
  File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 188, in _trim_results
    new_result['Title'] = self._reformat_release_name( new_result['Title'] )
  File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 197, in _reformat_release_name
    return re.search(release_name_re, release_name, re.IGNORECASE).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Every time I run this script for my series it keeps dying at this point.

Thoughts?

**Comment by BC44** [comment]
Seems a strange spot for the script to break. Would you mind going into your *.log file and pasting here (with your api key removed) the search URL corresponding to that particular query?

**Comment by Drazzilb08** [comment]
```
2021-02-22 08:13:22,746 - Module: CrossSeedAutoDL - Line: 344 - Message: Searching for 124 of 1872: Danny Phantom / Danny Phantom Season 3

2021-02-22 08:13:22,746 - Module: CrossSeedAutoDL - Line: 113 - Message: http://192.168.1.200:9117/api/v2.0/indexers/all/results?apikey=<API Key>&Query=Danny+Phantom&Tracker%5B%5D=beyond-hd-oneurl%2Canimebytes%2Cbroadcasthenet&Category%5B%5D=5000&season=3

```
Well I moved those files out for the original show to make sure it was the search query or the files their selves. However came across it again with a different TV Show.
Exact same error though with this one:

```
Searching for 124 of 1872: Danny Phantom
Traceback (most recent call last):
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 375, in
main()
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 347, in main
matching_results = searcher.search(local_release_data, search_history)
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 137, in search
self.search_results = self._trim_results( resp_json['Results'] )
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 188, in _trim_results
new_result['Title'] = self._reformat_release_name( new_result['Title'] )
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 197, in _reformat_release_name
return re.search(release_name_re, release_name, re.IGNORECASE).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Script Finished Feb 22, 2021 08:13.23

```


Side note: The script works perfectly within my "movies" directory  the only tracker that is different between the two are BTN.

**Comment by Drazzilb08** [comment]
One thing I noticed, wonder if Its related, is that on my script not everything is being searched. (even on my movies script)
This Is what I'm using to call the script.

```
python3.9 CrossSeedAutoDL.py --strict-size -p -i /mnt/user/data/.torrents/movies -s /mnt/user/data/downloads/torrent_files/movies -u http://192.168.1.200:9117 -k <api> -t beyond-hd-oneurl,hdtorrents, passthepopcorn,animebytes
```
I noticed this by looking at the `Search History` which only shows PTP and AB

Example of the search url.
```
2021-02-22 00:01:44,109 - Module: CrossSeedAutoDL - Line: 113 - Message: http://192.168.1.200:9117/api/v2.0/indexers/all/results?apikey=<API>&Query=Despicable+Me+3+2017&Tracker%5B%5D=beyond-hd-oneurl%2Chdtorrents%2Cpassthepopcorn%2Canimebytes&Category%5B%5D=2000
```

**Comment by BC44** [comment]
The script dying is fixed in b326ea5619eded56bcdae5534c3ba96015a65ed5. 

In `SearchHistory.json`, the items under `download_history` would be the items that were downloaded, It's possible that matches just weren't found in the search results in those trackers to download.

**Comment by Drazzilb08** [comment]
> The script dying is fixed in [b326ea5](https://github.com/BC44/Cross-Seed-AutoDL/commit/b326ea5619eded56bcdae5534c3ba96015a65ed5).

I'll give this a go. I'll let you know what I find. (hopefully nothing)

**Comment by Drazzilb08** [comment]
No luck, still having issues.
```
Searching for 123 of 1873: Danny Phantom
Traceback (most recent call last):
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 384, in
main()
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 355, in main
matching_results = searcher.search(local_release_data, search_history)
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 137, in search
self.search_results = self._trim_results( resp_json['Results'] )
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 189, in _trim_results
new_result['Title'] = self._reformat_release_name( new_result['Title'] )
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 203, in _reformat_release_name
log.info(f'"{release_name}" name could not be trimmed down')
NameError: name 'log' is not defined
Script Finished Feb 23, 2021 16:29.46
```
```
2021-02-23 16:29:43,464 - Module: CrossSeedAutoDL - Line: 352 - Message: Searching for 123 of 1873: Danny Phantom / Danny Phantom Season 3

2021-02-23 16:29:43,475 - Module: CrossSeedAutoDL - Line: 113 - Message: http://192.168.1.200:9117/api/v2.0/indexers/all/results?apikey=<API>&Query=Danny+Phantom&Tracker%5B%5D=beyond-hd-oneurl%2Canimebytes%2Cbroadcasthenet&Category%5B%5D=5000&season=3
```

If there is something else I can do to help with this please let me know.

**Comment by BC44** [comment]
This was just a typo, sorry for the error. I've fixed it in 1f6cc1e55ef81de2b2bd840f297edf255651c1f1

**Comment by BC44** [comment]
Though I would be interested to know what the release titles are that are causing the crash. Would you be able to paste the lines from the log file that say `"<insert_title>" name could not be trimmed down` when you can? Thanks in advance

**Comment by Drazzilb08** [comment]
That's just it the release folder simply has `Danny Phantom Season 3` and the files within are labeled `Danny Phantom - S03E01 - Eye for an Eye WEBRip-720p` as such.
Here is a paste of the entire log file: https://paste.ubuntu.com/p/PqG5twKCxS/

**Comment by BC44** [comment]
Sorry, I didn't communicate exactly what the issue was properly before. The release title that needed to be trimmed in the script is not the local file title, but the release title of the search result. I've added a logging entry in the new version of the script to log when that happens.

**Comment by Drazzilb08** [comment]
Right. I'll keep an eye out for that. **IF** there are any issues I'll be sure to paste that in. **IF** not then I'll let you know.

**Comment by Drazzilb08** [comment]
Well it seems too have moved past the spot. However, new issue. 
```
Traceback (most recent call last):
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 384, in
main()
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 355, in main
matching_results = searcher.search(local_release_data, search_history)
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 115, in search
resp = requests.get(search_url, local_release_data)
File "/usr/lib64/python3.9/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/lib64/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib64/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib64/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/lib64/python3.9/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.200', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey=<api>&Query=My+Little+Pony&Tracker%5B%5D=beyond-hd-oneurl%2Canimebytes%2Cbroadcasthenet&Category%5B%5D=5000&season=2&main_path=%2Fmnt%2Fuser%2Fdata%2F.torrents%2Fseries%2FMy+Little+Pony+-+Friendship+Is+Magic+S02+1080p+Netflix+WEB-DL+DD%2B+5.1+x264-TrollHD&basename=My+Little+Pony+-+Friendship+Is+Magic+S02+1080p+Netflix+WEB-DL+DD%2B+5.1+x264-TrollHD&size=19062244781&guessed_data=title&guessed_data=alternative_title&guessed_data=season&guessed_data=screen_size&guessed_data=streaming_service&guessed_data=source&guessed_data=audio_codec&guessed_data=audio_channels&guessed_data=video_codec&guessed_data=release_group&guessed_data=type (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))
```

Seems like it occurs when one of the trackers goes down for a moment or two on Jackett.  I can make a new issue out of this as I feel the original one is done.

**Comment by Drazzilb08** [comment]
Created new issue #13 I'm gonna consider this particular issue closed. I'll still provide a log file with the Trimmed down segments as soon as I can get the script to make a complete cycle.
